# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(f'NumPy version = {np.__version__}\n\nConfiguration =\n')
np.__config__.show()

NumPy version = 1.19.5

Configuration =

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))
# Include your solution below

print(f'Memory size = {Z.itemsize * Z.size}')

Memory size = 3072


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
# excluding 58
np.arange(10, 58, dtype='int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57])

**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)
# Include your solution below
a = np.flip(a)
print(a)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))
# Include your solution below
np.amax(Z, axis = 0)


array([0.954212  , 0.7306921 , 0.80835602, 0.94243331, 0.89101008,
       0.9383299 , 0.98528875, 0.90207733, 0.82329925, 0.66662926,
       0.95186092])

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
np.pad(np.zeros((5,5)), 1, constant_values=1)


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, 1, constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [13]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print("Original = ", Z)
Y = Z.astype('int')
print("\nExtracted = ", Y)

Original =  [0.60010581 6.54212899 5.62431466 2.22035596 2.99617373 5.35967709
 0.95792524 5.71576858 9.98273194 6.75786353]

Extracted =  [0 6 5 2 2 5 0 5 9 6]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [14]:
R = np.arange(0, 5)
C = np.ones((5, 1))

R * C

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [15]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**15. Create a random vector of size 10 and sort it**

In [16]:
np.random.seed(10)
Z = np.random.rand(10)
print('Before sorting\n', Z)

Z.sort()
print('\nAfter sorting\n', Z)

Before sorting
 [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]

After sorting
 [0.02075195 0.08833981 0.16911084 0.19806286 0.22479665 0.49850701
 0.63364823 0.74880388 0.76053071 0.77132064]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below


**17. Create random vector of size 10 and replace the maximum value by 0**

In [ ]:
np.random.random(10)

**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
Z = np.arange(5)[::-1]
# Include your solution below


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    