# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(f'NumPy version = {np.__version__}\n\nConfiguration =\n')
np.__config__.show()

NumPy version = 1.19.5

Configuration =

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))

# ndarray.itemsize returns the length of one array element in bytes
# ndarray.size returns the length of the ndarray
# their product would be the memory size of the array
print(f'Memory size = {Z.itemsize * Z.size}')

Memory size = 3072


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
# Range 10 to 58, both included
np.arange(10, 58+1, dtype='int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)

print("original = {}".format(a))

flipped = np.flip(a)
print("flipped  = {}".format(flipped))

original = [0 1 2 3 4 5 6 7 8 9]
flipped  = [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))

# np.amax returns maximum of an array along an axis
# axis=0 would find the maxima along the first axis
max_values = np.amax(Z, axis=0)

print(max_values)

[0.90293113 0.86162693 0.78992008 0.9595141  0.98780796 0.89416886
 0.96993776 0.91729091 0.91236263 0.75004473 0.81730283]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
# create a 5x5 matrix with zeros everywhere
array_no_padding = np.zeros((5,5))

pad_width = 1
value_to_pad = 1

# np.pad adds values to the edges of each axis. In this case the padding width
# is 1 and it pads with 1s, creating a 7x7 array with 1s on the borders and 0s
# everywhere else
np.pad(array_no_padding, pad_width, constant_values=value_to_pad)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below

pad_width = 1
value_to_pad = 0

# np.pad adds values to the edges of each axis. In this case the padding width
# is 1 and it pads with 0s, creating a 7x7 array with 0s on the borders and 1s
# everywhere else
np.pad(Z, pad_width, constant_values=value_to_pad)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [13]:
Z = np.random.uniform(0, 10, 10)

print("Original = ", Z)

type_to_cast_to = 'int'

# astype casts an array to the given dtype
Z_as_integer = Z.astype(dtype=type_to_cast_to)

print("Extracted = ", Z_as_integer)

Original =  [7.22601984 3.16863593 7.60358731 0.13623878 6.55168957 4.83693827
 2.17770402 8.51404561 2.10222646 3.04423353]
Extracted =  [7 3 7 0 6 4 2 8 2 3]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [14]:
# The given matrix can be seen as a matrix product of two matrices

# Creates the left matrix
left_matrix = np.arange(0, 5)

# Creates the right matrix
right_matrix = np.ones((5, 1))

# Multiply both matrices to obtain the desired output
left_matrix * right_matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [15]:
start_value = 0
end_value = 1
size = 11

# By creating a vector with size 11, not taking the first element
# and setting the endpoint property to false (this causes the end_value to not 
# be included in the sequence) we obtain the desired vector
vector = np.linspace(start_value, end_value, size, endpoint=False)[1:]

print("Vector = ", vector)
print("Size of vector = {}".format(len(vector)))

Vector =  [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
Size of vector = 10


**15. Create a random vector of size 10 and sort it**

In [16]:
size_to_create = 10

random_vector = np.random.rand(size_to_create)
print('Before sorting\n', random_vector)

sorted_vector = np.sort(random_vector)
print('\nAfter sorting\n', sorted_vector)

Before sorting
 [0.6384949  0.84727297 0.44250266 0.59534046 0.91519615 0.33274428
 0.45305346 0.01980825 0.86349995 0.55498311]

After sorting
 [0.01980825 0.33274428 0.44250266 0.45305346 0.55498311 0.59534046
 0.6384949  0.84727297 0.86349995 0.91519615]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [17]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

print('Cartesian\n', Z)

# to get the rho (R) component, we need to find the hypotenuse of the two components
R = np.hypot(X, Y)

# to get the theta (T) component, we need to find the arc tangent of the two components
# theta is in radians
T = np.arctan2(Y, X)

# stack the R and T together just like Z
Z_polar = np.stack([R, T], axis=1)

print('\nPolar\n', Z_polar)

Cartesian
 [[0.36303698 0.38927378]
 [0.3328296  0.35163292]
 [0.70095935 0.55757976]
 [0.67877407 0.24276336]
 [0.64621802 0.19491325]
 [0.35611055 0.76648345]
 [0.11857413 0.27300541]
 [0.21201573 0.69683271]
 [0.81568576 0.99559178]
 [0.84396603 0.32655452]]

Polar
 [[0.53228744 0.82025898]
 [0.48417069 0.81286292]
 [0.89567806 0.67196183]
 [0.72088022 0.3434734 ]
 [0.67497327 0.29294375]
 [0.84516957 1.13586509]
 [0.29764371 1.16105065]
 [0.7283725  1.27543927]
 [1.28706886 0.88439893]
 [0.90494006 0.36918731]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [18]:
random_vector = np.random.random(10)

print('Original = ', random_vector)

# argmax returns the idx of the max value
idx_max_value = random_vector.argmax()

print('\nMax value idx = {}'.format(idx_max_value))

#replacing the max value with zero
random_vector[idx_max_value] = 0

print('\nMax replaced = ', random_vector)

Original =  [0.78014875 0.55756352 0.54124224 0.66041302 0.04045828 0.73734484
 0.24894837 0.31839544 0.57484971 0.84878526]

Max value idx = 9

Max replaced =  [0.78014875 0.55756352 0.54124224 0.66041302 0.04045828 0.73734484
 0.24894837 0.31839544 0.57484971 0.        ]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [19]:
Z = np.random.uniform(0,1,10)
z = 0.5

print("Original array = ", Z)

# Returns an array in which the elements are the abs differences of the elements
# of the original array from the given value
differences_array = (np.abs(Z - z))

print("\nDifferences array = ", differences_array)

# argmin returns the idx of the min value
idx_min_value = differences_array.argmin()

# The idx that holds the smallest value in differences_array is the idx of the
# nearest value in the original array
print("\nIdx of the nearest value = {}".format(idx_min_value))

nearest_value = Z[idx_min_value]

print("\nNearest value = {}".format(nearest_value))

Original array =  [0.80274498 0.55894832 0.67612869 0.1410997  0.371652   0.69558597
 0.99061068 0.09960182 0.79605199 0.94982736]

Differences array =  [0.30274498 0.05894832 0.17612869 0.3589003  0.128348   0.19558597
 0.49061068 0.40039818 0.29605199 0.44982736]

Idx of the nearest value = 1

Nearest value = 0.5589483208901141


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [20]:
Z = np.arange(5)[::-1]

Z = [5,4,3,2,1]     # The one above produce [4,3,2,1,0]

# calculate the size that the new vector will have
size_new_vector = len(Z) + 3*(len(Z)-1)

# create an array with all zeros
all_zeros = np.zeros(size_new_vector)

# returns every other (3+1) element in the all_zeros array
# this element will be replaced by the elements of original array
all_zeros[::3+1] = Z

print("Zeros interleaved = {}".format(all_zeros))

Zeros interleaved = [5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

# Break down 5x5 matrix to 5 5x1 to match the dimensions of matrix A for multiplication
C = B[:, :, None]

# Multiply A with C is where each value within 5x1 in C is multiply to each row within matrix A
D = A * C

# print("\nA = ", A)
# print("\nB = ", B)
# print("\nC = ", C)
print("\nD = ", D)


D =  [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [22]:
W = np.arange(30).reshape(6,5)

print("Before swap =\n", W)

# W[[0,1]] is the first and second rows in order
# W[[1,0]] is the first and second rows reversed
# Just needs to replace one by other

W[[0,1]] = W[[1,0]]
print("\nAfter swap =\n", W)

Before swap =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

After swap =
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [23]:
def bbox(img):
    # include your solution below
    # Filter to where the actual image is (which is when the value is not False) and assign to X. 
    # This leads to the first array being x values and the second array being y values
    X = np.where(img != 0)
    
    # Then take the corners of x and y values using min and max on X[0] and X[1]
    r1 = np.min(X[0])
    c1 = np.min(X[1])
    r2 = np.max(X[0])
    c2 = np.max(X[1])
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [24]:
def moving_average(x, N=3):
    # pads the array with zeros if the length of the array is not a multiple
    # of the size of the moving average
    if len(x)%N !=0:
      size_of_the_pad = N - len(x) % N

      value_to_pad = 0    

      x = np.pad(x, (0, size_of_the_pad ), constant_values=value_to_pad)
 
    # creates arrays of size N by slicing the original array
    # sub_arrays will be an array of arrays of size N
    sub_arrays = [x[idx:idx+N] for idx,value in enumerate(x) if idx%N==0]

    # create a new array in which each element is the mean of each array of size N
    # in the sub_arrays
    return [np.mean(array) for array in sub_arrays]

a = [1,2,3,4,5,6,7,8,9]
N = 3
print(moving_average(a, N))

[2.0, 5.0, 8.0]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [25]:
C = np.bincount([1,1,2,3,4,4,6])

print("C = {}".format(C))
# C = [0 2 1 1 2 0 1]

# Starting from C we need to obtain the original array A, since np.bincount(A) == C
# So in C, a 0 in idx 0 indicates that the original array has 0 zero times,
# a 2 in the idx 1 indicates that the original array has 1 two times,
# a 1 in the idx 2 indicates that the original array has 2 one time, and so on.

# So basically we need to repeat the idx of each value of C as many times as the values at that idx in C using np.repeat
C_idx = np.arange(C.size)

A = np.repeat(a=C_idx, repeats=C)

print("A = {}".format(A))
print("np.bincount(A) = {}".format(np.bincount(A)))
print("C =              {}".format(C))

C = [0 2 1 1 2 0 1]
A = [1 1 2 3 4 4 6]
np.bincount(A) = [0 2 1 1 2 0 1]
C =              [0 2 1 1 2 0 1]


**25. Find the most frequent value in the array below?**

In [26]:
Z = np.random.randint(0,10,50)
# Include your solution below

print("Sorted Z       = {}".format(np.sort(Z)))

# using bincounts to count the occurrence of each value
counts = np.bincount(Z)

print("\nnp.bincount(Z) = {}".format(counts))

# using argmax to the max occurred value (which is the idx in bincount)
print("\nMost frequent value = {}".format(np.argmax(counts)))

Sorted Z       = [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 4 4 4 4 4 5 5 5 5 6
 6 7 7 7 7 8 8 8 9 9 9 9 9]

np.bincount(Z) = [ 5 11  7  4  5  4  2  4  3  5]

Most frequent value = 1


**26. Write a function to return the n largest values of an array** 

In [27]:
def nlargest(a,n = 5):
    # argsort returns the indices of array a, of which we are going to take the last n indices, then we return the array a
    # of those repected indices
    return a[a.argsort()[-n:]]


Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)
print(nlargest(Z,n))    

[3389 6442 3727 ... 3090 8428 7860]
[9995 9996 9997 9998 9999]
